# -*- coding: utf-8 -*-
# Ghidra Jython 2 script. Decompiles a batch of opcode handlers
# whose audit-shape verdict was "mixed" or "no-clear-pattern" and
# need byte-level inspection to classify their write semantics.
#
# Output: /out/handler_decompiles.md
# pylint: disable=undefined-variable

# @author wow-client-toolkit
# @category Analysis
# @runtime Jython

from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor
import os

OUT_PATH = os.environ.get("DH_OUT", "/out/handler_decompiles.md")

cp = currentProgram
fm = cp.getFunctionManager()
af = cp.getAddressFactory()

decomp = DecompInterface()
decomp.setOptions(DecompileOptions())
decomp.openProgram(cp)

lines = []


def out(s):
    lines.append(s)


HANDLERS = [
    # 23 NEW packet-handlers from full-caller audit
    ("0x254 SMSG_ZONE_UNDER_ATTACK", "0x0050c3c0"),
    ("0x33A SMSG_DEFENSE_MESSAGE", "0x0050c850"),
    ("0x1D9 SMSG_START_MIRROR_TIMER", "0x00519a50"),
    ("0x3AE MSG_RAID_READY_CHECK_CONFIRM", "0x005744f0"),
    ("0x322 MSG_RAID_READY_CHECK", "0x00574d50"),
    ("0x25C SMSG_AUCTION_LIST_RESULT", "0x0059e160"),
    ("0x25D SMSG_AUCTION_OWNER_LIST_RESULT", "0x0059e480"),
    ("0x265 SMSG_AUCTION_BIDDER_LIST_RESULT", "0x0059ecd0"),
    ("0x25B SMSG_AUCTION_COMMAND_RESULT", "0x0059ffb0"),
    ("0x25E SMSG_AUCTION_BIDDER_NOTIFICATION", "0x005a0480"),
    ("0x46A SMSG_CRITERIA_UPDATE", "0x005b3160"),
    ("0x47D SMSG_ALL_ACHIEVEMENT_DATA", "0x005b32f0"),
    ("0x501 SMSG_QUERY_QUESTS_COMPLETED_RESPONSE", "0x005b5190"),
    ("0x4AA SMSG_PET_GUIDS", "0x005d6550"),
    ("0x377 MSG_INSPECT_ARENA_TEAMS", "0x005e7b00"),
    ("0x209 SMSG_ACCOUNT_DATA_TIMES", "0x006b94c0"),
    ("0x092 SMSG_GUILD_EVENT", "0x006d92d0"),
    ("0x41E SMSG_SEND_UNLEARN_SPELLS", "0x006e2240"),
    ("0x203 SMSG_REMOVED_SPELL", "0x006e7840"),
    ("0x12C SMSG_SUPERCEDED_SPELL", "0x006e7e00"),
    ("0x262 SMSG_DISPEL_FAILED", "0x00750ea0"),
    ("0x134 SMSG_SPELL_COOLDOWN", "0x00806dd0"),
    ("0x298 SMSG_RESET_RANGED_COMBAT_TIMER", "0x008071c0"),
    # 12 indirectly-reachable (called from packet handlers)
    ("0x1BC indirect via SMSG_PETITION_SHOWLIST", "0x006d6d20"),
    ("0x185 indirect via SMSG_QUESTGIVER_QUEST_LIST -- 3x", "0x006d0240"),
    ("0x185 indirect via SMSG_QUESTGIVER_QUEST_LIST -- 3x", "0x006d0460"),
    ("0x185 indirect via SMSG_QUESTGIVER_QUEST_LIST -- 3x", "0x006d0ab0"),
    ("0x160 indirect via SMSG_LOOT_RESPONSE", "0x006d53b0"),
    ("0x131 indirect via SMSG_SPELL_START", "0x0080e1b0"),
    ("0x143 indirect via SMSG_ATTACKSTART", "0x00755630"),
    ("0x0A9 indirect via SMSG_UPDATE_OBJECT", "0x004d7100"),
    ("0x09B indirect via FUN_00505dc0", "0x00503990"),
    ("0x096 + 0x3B3 indirect", "0x0050be70"),
    ("0x436 indirect via SMSG_CALENDAR_SEND_CALENDAR", "0x005c29c0"),
    ("0x1EC indirect via SMSG_AUTH_CHALLENGE 2-deep", "0x005f79a0"),
    # 9 new memcpy/memmove-using handlers (non-CDataStore primitives)
    ("0x244 SMSG_ITEM_TEXT_QUERY_RESPONSE", "0x00635a40"),
    ("0x20E SMSG_CHANGEPLAYER_DIFFICULTY_RESULT", "0x0052c460"),
    ("0x28D SMSG_AUCTION_REMOVED_NOTIFICATION", "0x005a0ac0"),
    ("0x496 SMSG_AURA_UPDATE", "0x007300a0"),
    ("0x3C5 SMSG_KICK_REASON", "0x004d9500"),
    ("0xFD opcode-unknown", "0x00530920"),
    ("0x39E SMSG_VOICE_SESSION_ROSTER_UPDATE", "0x006ccf10"),
    ("0x239 SMSG_SEND_MAIL_RESULT", "0x005717b0"),
    ("0x17D SMSG_GOSSIP_MESSAGE", "0x0058b1b0"),
    # 14 still-truly-unreached score-4 (placeholder for completeness)
    ("(unreached) 0x004d5550", "0x004d5550"),
    ("(unreached) 0x004d7230", "0x004d7230"),
    ("(unreached) 0x004f4ae0", "0x004f4ae0"),
    ("(unreached) 0x005bf030", "0x005bf030"),
    ("(unreached) 0x005bf250", "0x005bf250"),
    ("(unreached) 0x005c07e0", "0x005c07e0"),
    ("(unreached) 0x005c0cf0", "0x005c0cf0"),
    ("(unreached) 0x006d08f0", "0x006d08f0"),
    ("(unreached) 0x006d58d0", "0x006d58d0"),
    ("(unreached) 0x006d6050", "0x006d6050"),
    ("(unreached) 0x006d8870", "0x006d8870"),
    ("(unreached) 0x0072f5d0", "0x0072f5d0"),
    ("(unreached) 0x00806700", "0x00806700"),
    ("(unreached) 0x0098d910", "0x0098d910"),
]

out("# Mixed-pattern handler decompiles")
out("")
out("Generated by `decompile_handlers.py`. Each handler was flagged")
out("by `find_write_primitives.py` at score >= 5 but the heuristic")
out("byte-pattern classification couldn't decide if the destination")
out("is a heap-vec (DoS-only) or a fixed-globals scratch area")
out("(potentially exploitable). The decompile shows the actual")
out("write logic.")
out("")

for label, va_str in HANDLERS:
    out("## {0} -- `{1}`".format(label, va_str))
    out("")
    addr = af.getAddress(va_str)
    fn = fm.getFunctionAt(addr)
    if fn is None:
        out("(no function defined)")
        out("")
        continue
    out("Size: {0} bytes".format(fn.getBody().getNumAddresses()))
    out("")
    out("```c")
    res = decomp.decompileFunction(fn, 90, ConsoleTaskMonitor())
    if res.decompileCompleted():
        c = res.getDecompiledFunction().getC()
        # Cap at 200 lines per function so the report stays scanable.
        for ln in c.splitlines()[:200]:
            out(ln)
    out("```")
    out("")

out_dir = os.path.dirname(OUT_PATH)
if out_dir and not os.path.isdir(out_dir):
    try:
        os.makedirs(out_dir)
    except Exception:
        pass
try:
    f = open(OUT_PATH, "w")
    f.write("\n".join(lines))
    f.close()
    print("[decompile_handlers] wrote " + OUT_PATH + " (" + str(len(lines)) + " lines)")
except Exception as e:
    print("[decompile_handlers] write failed: " + str(e))
    print("\n".join(lines))
