# -*- coding: utf-8 -*-
# Ghidra Jython 2 script. Decompiles a batch of opcode handlers
# whose audit-shape verdict was "mixed" or "no-clear-pattern" and
# need byte-level inspection to classify their write semantics.
#
# Output: /out/handler_decompiles.md
# pylint: disable=undefined-variable

# @author wow-client-toolkit
# @category Analysis
# @runtime Jython

from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor
import os

OUT_PATH = os.environ.get("DH_OUT", "/out/handler_decompiles.md")

cp = currentProgram
fm = cp.getFunctionManager()
af = cp.getAddressFactory()

decomp = DecompInterface()
decomp.setOptions(DecompileOptions())
decomp.openProgram(cp)

lines = []


def out(s):
    lines.append(s)


HANDLERS = [
    ("0x0A9 SMSG_UPDATE_OBJECT", "0x004d73a0"),
    ("0x08A SMSG_GUILD_ROSTER", "0x005cc5d0"),
    ("0x12A SMSG_INITIAL_SPELLS", "0x006df050"),
    ("0x179 SMSG_PET_SPELLS", "0x005d6b90"),
    ("0x23B SMSG_MAIL_LIST_RESULT", "0x00571c50"),
    ("0x25F SMSG_AUCTION_OWNER_NOTIFICATION", "0x005a0790"),
    ("0x26F MSG_LIST_STABLED_PETS", "0x005a11a0"),
    ("0x2CC SMSG_RAID_INSTANCE_INFO", "0x00501030"),
    ("0x2D4 SMSG_BATTLEFIELD_STATUS", "0x0054ae40"),
    ("0x332 SMSG_EXPECTED_SPAM_RECORDS", "0x00501c70"),
    ("0x360 SMSG_UPDATE_LFG_LIST", "0x0055b770"),
    ("0x3B8 SMSG_COMMENTATOR_MAP_INFO", "0x0056bf30"),
    ("0x3BB SMSG_COMMENTATOR_PLAYER_INFO", "0x0056b280"),
    ("0x3F1 SMSG_USERLIST_REMOVE", "0x005042f0"),
    ("0x3F2 SMSG_USERLIST_UPDATE", "0x00500380"),
    ("0x44A SMSG_NOTIFY_DANCE", "0x00576730"),
    ("0x4BC SMSG_EQUIPMENT_SET_LIST", "0x005af490"),
    ("0x_SHARED_31 (FUN_00526530)", "0x00526530"),
    ("0x_SHARED_48 (FUN_006e2e90)", "0x006e2e90"),
]

out("# Mixed-pattern handler decompiles")
out("")
out("Generated by `decompile_handlers.py`. Each handler was flagged")
out("by `find_write_primitives.py` at score >= 5 but the heuristic")
out("byte-pattern classification couldn't decide if the destination")
out("is a heap-vec (DoS-only) or a fixed-globals scratch area")
out("(potentially exploitable). The decompile shows the actual")
out("write logic.")
out("")

for label, va_str in HANDLERS:
    out("## {0} -- `{1}`".format(label, va_str))
    out("")
    addr = af.getAddress(va_str)
    fn = fm.getFunctionAt(addr)
    if fn is None:
        out("(no function defined)")
        out("")
        continue
    out("Size: {0} bytes".format(fn.getBody().getNumAddresses()))
    out("")
    out("```c")
    res = decomp.decompileFunction(fn, 90, ConsoleTaskMonitor())
    if res.decompileCompleted():
        c = res.getDecompiledFunction().getC()
        # Cap at 200 lines per function so the report stays scanable.
        for ln in c.splitlines()[:200]:
            out(ln)
    out("```")
    out("")

out_dir = os.path.dirname(OUT_PATH)
if out_dir and not os.path.isdir(out_dir):
    try:
        os.makedirs(out_dir)
    except Exception:
        pass
try:
    f = open(OUT_PATH, "w")
    f.write("\n".join(lines))
    f.close()
    print("[decompile_handlers] wrote " + OUT_PATH + " (" + str(len(lines)) + " lines)")
except Exception as e:
    print("[decompile_handlers] write failed: " + str(e))
    print("\n".join(lines))
