# -*- coding: utf-8 -*-
# Ghidra Jython 2 script. Decompiles a batch of opcode handlers
# whose audit-shape verdict was "mixed" or "no-clear-pattern" and
# need byte-level inspection to classify their write semantics.
#
# Output: /out/handler_decompiles.md
# pylint: disable=undefined-variable

# @author wow-client-toolkit
# @category Analysis
# @runtime Jython

from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor
import os

OUT_PATH = os.environ.get("DH_OUT", "/out/handler_decompiles.md")

cp = currentProgram
fm = cp.getFunctionManager()
af = cp.getAddressFactory()

decomp = DecompInterface()
decomp.setOptions(DecompileOptions())
decomp.openProgram(cp)

lines = []


def out(s):
    lines.append(s)


HANDLERS = [
    ("0x34E SMSG_ARENA_TEAM_ROSTER", "0x005a3e10"),
    ("0x35B SMSG_ARENA_TEAM_STATS", "0x005a2d50"),
    ("0x3E8 SMSG_GUILD_BANK_LIST", "0x005a7250"),
    ("0x3FD MSG_GUILD_PERMISSIONS", "0x005cb9f0"),
]

out("# Mixed-pattern handler decompiles")
out("")
out("Generated by `decompile_handlers.py`. Each handler was flagged")
out("by `find_write_primitives.py` at score >= 5 but the heuristic")
out("byte-pattern classification couldn't decide if the destination")
out("is a heap-vec (DoS-only) or a fixed-globals scratch area")
out("(potentially exploitable). The decompile shows the actual")
out("write logic.")
out("")

for label, va_str in HANDLERS:
    out("## {0} -- `{1}`".format(label, va_str))
    out("")
    addr = af.getAddress(va_str)
    fn = fm.getFunctionAt(addr)
    if fn is None:
        out("(no function defined)")
        out("")
        continue
    out("Size: {0} bytes".format(fn.getBody().getNumAddresses()))
    out("")
    out("```c")
    res = decomp.decompileFunction(fn, 90, ConsoleTaskMonitor())
    if res.decompileCompleted():
        c = res.getDecompiledFunction().getC()
        # Cap at 200 lines per function so the report stays scanable.
        for ln in c.splitlines()[:200]:
            out(ln)
    out("```")
    out("")

out_dir = os.path.dirname(OUT_PATH)
if out_dir and not os.path.isdir(out_dir):
    try:
        os.makedirs(out_dir)
    except Exception:
        pass
try:
    f = open(OUT_PATH, "w")
    f.write("\n".join(lines))
    f.close()
    print("[decompile_handlers] wrote " + OUT_PATH + " (" + str(len(lines)) + " lines)")
except Exception as e:
    print("[decompile_handlers] write failed: " + str(e))
    print("\n".join(lines))
