# -*- coding: utf-8 -*-
# Ghidra Jython 2 script. Hunts for OTHER write-primitive RCE
# patterns of the same shape as the MSG_BATTLEGROUND_PLAYER_POSITIONS
# vuln (write-target derived from packet-controlled count via LEA
# scaled-index arithmetic, in an unbounded loop).
#
# Strategy:
#   1. Identify CDataStore::GetXxx functions that LOOK like write
#      primitives: their first argument (after `this`) is a pointer
#      that gets dereferenced + written to.
#   2. For each call site, inspect the surrounding 64 bytes of
#      machine code for the danger pattern:
#        - `lea reg, [reg*N + imm]` where N >= 2 (scaled-index)
#        - inside or just after a backward conditional jump (loop)
#   3. Score and report ranked candidates so the operator knows
#      which call sites need the same loop-cap patch the BG handler
#      got.
#
# Output: /out/write_primitives.md
# pylint: disable=undefined-variable

# @author wow-exe-patcher
# @category Analysis
# @runtime Jython

from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor
import os

OUT_PATH = os.environ.get("WP_OUT", "/out/write_primitives.md")

cp = currentProgram
fm = cp.getFunctionManager()
af = cp.getAddressFactory()
listing = cp.getListing()
ref_mgr = cp.getReferenceManager()
sym_table = cp.getSymbolTable()

decomp = DecompInterface()
decomp.setOptions(DecompileOptions())
decomp.openProgram(cp)

lines = []


def out(s):
    lines.append(s)


def addr(va):
    return af.getAddress(va)


# Known write-primitives in Wow.exe build 12340. We seed with the
# canonical writeup-named one (CDataStore::GetInt64 @ 0x0047B400)
# and then look for sister functions (GetInt32, GetFloat, GetBytes)
# at small offsets from the same vtable / module section.
# Functions that write through a pointer argument. We start with
# CDataStore::GetInt64 (writeup-named) and add GetInt32/GetFloat
# (sister methods on CDataStore that follow the exact same shape:
# `Get(this, dst*)` reads sizeof(T) bytes from this->buffer and
# writes them to *dst). All three are write primitives if `dst`
# is attacker-controllable.
#
# The other CDataStore::GetXxx entry points are at small offsets
# from GetInt64 by linker layout. We resolve them by scanning the
# nearby code blocks below if symbol resolution fails.
SEED = [
    ("CDataStore::GetInt64", "0x0047B400"),
    ("CDataStore::GetInt32", "0x0047B450"),
    ("CDataStore::GetFloat", "0x0047B330"),
]

out("# Wow.exe write-primitive RCE audit")
out("")
out("Generated by `find_write_primitives.py` postscript. Looks for")
out("functions that write to a pointer argument and are called in")
out("a loop where the destination is computed via `lea reg, [reg*N + imm]`")
out("(scaled-index arithmetic) -- the same shape as the documented")
out("MSG_BATTLEGROUND_PLAYER_POSITIONS arbitrary-write.")
out("")

# ---- 1. Discover sister write-primitives ----------------------------
out("## 1. Write-primitive functions (seeded from CDataStore::GetInt64)")
out("")

PRIMITIVES = []
for name, va_hex in SEED:
    va = addr(va_hex)
    fn = fm.getFunctionAt(va)
    if fn is not None:
        PRIMITIVES.append((name, va_hex, fn))
        out("- `{0}` @ `{1}` (size {2} bytes)".format(
            name, va_hex, fn.getBody().getNumAddresses()))
    else:
        out("- `{0}` @ `{1}` -- NOT defined as a function (run autoanalysis)".format(name, va_hex))
out("")

# Look for sister functions in the same .text neighborhood that
# match the GetInt64 prologue (push esi; mov esi, ecx; ...).
# These are the most likely sister write-primitives.
out("## 2. Sister write-primitive candidates (same-prototype neighbors)")
out("")
seed_fn = PRIMITIVES[0][2] if PRIMITIVES else None
neighbors = []
if seed_fn is not None:
    seed_entry = seed_fn.getEntryPoint()
    seed_size = seed_fn.getBody().getNumAddresses()
    # Walk backwards + forwards 0x800 bytes scanning for functions
    # with a 1-arg signature (after `this`) that call MSVC malloc
    # and look like CDataStore methods.
    delta = -0x800
    while delta <= 0x800:
        try:
            cand_addr = seed_entry.add(delta)
            f = fm.getFunctionContaining(cand_addr)
            if f is not None and f.getEntryPoint() == cand_addr and f != seed_fn:
                proto = f.getPrototypeString(False, False)
                if "Get" in f.getName() or "CDataStore" in proto:
                    neighbors.append((f.getName(), str(cand_addr), proto))
        except Exception:
            pass
        delta += 4
    seen = set()
    for nm, ad, pr in neighbors:
        if ad in seen:
            continue
        seen.add(ad)
        out("- `{0}` @ `{1}` -- prototype `{2}`".format(nm, ad, pr))
if not neighbors:
    out("- (none found heuristically; rerun with explicit symbol seeds)")
out("")

# ---- 3. Audit every caller of every primitive -----------------------
out("## 3. Call-site audit (LEA scaled-index = danger pattern)")
out("")
out("For each call site, we score the surrounding 64 bytes of")
out("machine code:")
out("")
out("- **+3** if a `lea reg, [reg*N + imm32]` with N>=2 appears in the")
out("  instruction window (scaled-index destination)")
out("- **+2** if the basic block contains a backward conditional jump")
out("  (loop body)")
out("- **+2** if the same function reads from a global (`mov reg, [imm32]`)")
out("  and uses it as the loop bound (packet-controlled iteration count)")
out("")
out("Score >= 5 = same shape as the BG vuln. Score 3-4 = worth a manual")
out("look. Score 0-2 = local-variable destination, safe.")
out("")


def in_range(b, lo, hi):
    return lo <= b <= hi


def score_call_site(call_addr, owner_fn):
    score = 0
    notes = []
    body = owner_fn.getBody()

    # Scan 64 bytes back from the call for `lea reg32, [reg32*N + imm32]`.
    # x86 form: 8D /r with SIB byte where scale (top 2 bits) >= 1.
    block_start = call_addr.subtract(64)
    if not body.contains(block_start):
        block_start = body.getMinAddress()
    cur = block_start
    while cur is not None and cur.compareTo(call_addr) < 0:
        ins = listing.getInstructionAt(cur)
        if ins is None:
            cur = cur.next()
            continue
        mnem = ins.getMnemonicString().lower()
        if mnem == "lea":
            ops = ins.getDefaultOperandRepresentation(1)
            # Ghidra prints scale either as `*2` (decimal) or `*0x2`
            # (hex) depending on the listing format. Cover both.
            scale_markers = ("*0x2", "*0x4", "*0x8", "*2", "*4", "*8")
            if any(m in ops for m in scale_markers):
                score += 3
                notes.append("scaled-index LEA: `{0}`".format(ops))
                break
        cur = ins.getMaxAddress().next()

    # Backwards conditional jump in the parent function (loop)?
    fbody = owner_fn.getBody()
    it = listing.getInstructions(fbody, True)
    has_loop = False
    while it.hasNext():
        ins = it.next()
        m = ins.getMnemonicString().lower()
        if m.startswith("j") and m not in ("jmp",):
            for ref in ins.getReferencesFrom():
                tgt = ref.getToAddress()
                if tgt is not None and tgt.compareTo(ins.getAddress()) < 0:
                    if fbody.contains(tgt):
                        has_loop = True
                        break
            if has_loop:
                break
    if has_loop:
        score += 2
        notes.append("function contains a backward conditional jump (loop)")

    # Heuristic for global-loop-bound: any `mov reg, [imm32]` where
    # imm32 is a writable section + the same reg is used in cmp/test.
    it = listing.getInstructions(fbody, True)
    while it.hasNext():
        ins = it.next()
        if ins.getMnemonicString().lower() == "mov":
            ops = ins.getDefaultOperandRepresentation(1)
            if "DAT_" in ops or "[0x00" in ops:
                # rough: it's reading a global. Bonus +2.
                score += 2
                notes.append("reads global (`{0}`) -- candidate loop bound".format(ops))
                break

    return score, notes


for name, va_hex, fn in PRIMITIVES:
    out("### Callers of `{0}` @ `{1}`".format(name, va_hex))
    out("")
    refs = ref_mgr.getReferencesTo(fn.getEntryPoint())
    rows = []
    for ref in refs:
        if ref.getReferenceType().isCall():
            call_addr = ref.getFromAddress()
            owner = fm.getFunctionContaining(call_addr)
            if owner is None:
                continue
            sc, notes = score_call_site(call_addr, owner)
            rows.append((sc, call_addr, owner, notes))
    rows.sort(key=lambda r: -r[0])
    if not rows:
        out("- (no callers found)")
        out("")
        continue
    out("Total callers: {0}. Top 30 by danger score:".format(len(rows)))
    out("")
    for sc, call_addr, owner, notes in rows[:30]:
        marker = "DANGER" if sc >= 5 else ("REVIEW" if sc >= 3 else "ok")
        out("- score=**{0}** [{1}] call @ {2} in `{3}` @ {4}".format(
            sc, marker, call_addr, owner.getName(), owner.getEntryPoint()))
        for n in notes:
            out("    - {0}".format(n))
    out("")

# ---- 4. Decompile each DANGER caller ---------------------------------
out("## 4. Top-3 danger sites decompiled")
out("")
all_rows = []
for name, va_hex, fn in PRIMITIVES:
    refs = ref_mgr.getReferencesTo(fn.getEntryPoint())
    for ref in refs:
        if ref.getReferenceType().isCall():
            call_addr = ref.getFromAddress()
            owner = fm.getFunctionContaining(call_addr)
            if owner is None:
                continue
            sc, notes = score_call_site(call_addr, owner)
            all_rows.append((sc, call_addr, owner))
all_rows.sort(key=lambda r: -r[0])
seen_owners = set()
shown = 0
for sc, call_addr, owner in all_rows:
    key = str(owner.getEntryPoint())
    if key in seen_owners:
        continue
    seen_owners.add(key)
    if sc < 5 or shown >= 3:
        continue
    out("### `{0}` @ {1} -- score {2} -- call site {3}".format(
        owner.getName(), owner.getEntryPoint(), sc, call_addr))
    out("")
    out("```c")
    res = decomp.decompileFunction(owner, 60, ConsoleTaskMonitor())
    if res.decompileCompleted():
        c = res.getDecompiledFunction().getC()
        for ln in c.splitlines()[:120]:
            out(ln)
    out("```")
    out("")
    shown += 1

# Write
out_dir = os.path.dirname(OUT_PATH)
if out_dir and not os.path.isdir(out_dir):
    try:
        os.makedirs(out_dir)
    except Exception:
        pass
try:
    f = open(OUT_PATH, "w")
    f.write("\n".join(lines))
    f.close()
    print("[find_write_primitives] wrote " + OUT_PATH + " (" + str(len(lines)) + " lines)")
except Exception as e:
    print("[find_write_primitives] write failed: " + str(e))
    print("\n".join(lines))
